### ISSUE TITLE
这个库可以用于flv直播吗

### ISSUE THREAD

**Issue by Sam1141968878** [wangdaodao/vue-flv-player#2]

**Comment by wangdaodao** [comment]
这个只是对flvjs做了一个简单的封装，应该是可以使用的，但是具体我没有测试过，你可以试一试。我们这边使用的直播流格式是rtmp和hls的，我专门针对videojs也做了一个封装，https://github.com/wangdaodao/hrm-player 。issues关闭，有问题可以和我再探讨，谢谢支持。
